var publications_eng = [
	{
		'title': 'Fast and Flexible Multilegged Locomotion Using Learned Centroidal Dynamics',
		'representative_img': 'assets/publications/2020-fast-flexible/2020-fast-flexible.jpg',
		'conference_journal': 'SIGGRAPH',
		'year': 2020,
		'authors': 'Taesoo Kwon, Yoonsang Lee, Michiel van de Panne',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH 2020)',
		'video_iframe': '<iframe width="1280" height="749" src="https://www.youtube.com/embed/fGwMrRoC5bw" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'project_page': 'http://calab.hanyang.ac.kr/papers/flexLoco.html',
		'type': 'paper',
	},
	{
		'title': 'Control of an Iguana Character Using Soft-Body Simulation',
		'representative_img': 'assets/publications/2018-iguana-ctrl/2018-iguana-ctrl.jpg',
		'project_page': 'publications/2018-iguana-ctrl.html',
		'conference_journal': 'Access',
		'year': 2018,
		'authors': 'Taesoo Kwon, Hoimin Kim, Yoonsang Lee',
		'conference_journal_full': 'IEEE Access, Volume 6 Issue 1, Dec 2018',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/c37VEexDZaY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
	},
	{
		'title': 'Performance-Based Biped Control using a Consumer Depth Camera',
		'representative_img': 'assets/publications/2017-perf-based/2017-perf-based.png',
		'project_page': 'publications/2017-perf-based.html',
		'conference_journal': 'Eurographics',
		'year': 2017,
		'authors': 'Yoonsang Lee, Taesoo Kwon',
		'conference_journal_full': 'Computer Graphics Forum (Eurographics 2017), Volume 36 Issue 2, 387-395, May 2017',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/WVDPXdlnhBM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',

	},
	{
		'title': 'Push-Recovery Stability of Biped Locomotion',
		'representative_img': 'assets/publications/2015-push-recovery/2015-push-recovery.png',
		'project_page': 'publications/2015-push-recovery.html',
		'conference_journal': 'SIGGRAPH Asia',
		'year': 2015,
		'authors': 'Yoonsang Lee, Kyungho Lee, Soon-Sun Kwon, Jiwon Jeong, Carol O\'Sullivan, Moon Seok Park, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH Asia 2015), Volume 34 Issue 6, Article No. 180, November 2015',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/KrTDh5Zhlac" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',

	},
	{
		'title': 'Locomotion Control for Many-Muscle Humanoids',
		'representative_img': 'assets/publications/2014-many-muscle/2014-many-muscle.png',
		'project_page': 'publications/2014-many-muscle.html',
		'conference_journal': 'SIGGRAPH Asia',
		'year': 2014,
		'authors': 'Yoonsang Lee, Moon Seok Park, Taesoo Kwon, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH Asia 2014), Volume 33 Issue 6, Article No. 218, November 2014',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/O0zxRbZ_kNM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',

	},
	{
		'title': 'Data-Driven Biped Control',
		'representative_img': 'assets/publications/2010-data-driven/2010-data-driven.jpg',
		'project_page': 'publications/2010-data-driven.html',
		'conference_journal': 'SIGGRAPH',
		'year': 2010,
		'authors': 'Yoonsang Lee, Sungeun Kim, Jehee Lee',
		'conference_journal_full': 'ACM Transactions on Graphics (SIGGRAPH 2010), Volume 29 Issue 4, Article No. 129, July 2010',
		'video_iframe': '<iframe width="1017" height="765" src="https://www.youtube.com/embed/hpeqxc_1vwo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'paper',
	},
]
