var publications_kor = [
	{
		'title': '무게중심을 활용한 모션 생성 기술',
		'representative_img': 'assets/publications/domestic/2020-kcgsjournal-motion-com.png',
		'year': 2020,
		'authors': '박근태, 손채준, 이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 논문지, 제 26권 제 2호, 11-19, 2020.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2020-kcgsjournal-motion-com.pdf">[article]</a>',
		'type': 'paper',
	},
	{
		'title': '심층강화학습을 이용한 유한 상태 기반 보행 제어기의 학습',
		'representative_img': 'assets/publications/domestic/2019-kcgs-learning-fsm.png',
		'year': 2019,
		'authors': '강규철, 권태수, 이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 2019년 학술대회 논문집, 26-27, 2019.07.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-kcgs-learning-fsm.pdf">[article]</a>',
		'type': 'paper',
	},
	{
		'title': '보행 시뮬레이션을 위한 물리의 기초',
		'representative_img': 'assets/publications/domestic/2019-orthopaedic-walking-basic.png',
		'year': 2019,
		'authors': '이윤상',
		'conference_journal_full': 'Proceeding of 2019 SNU Orthopaedic Update(II): Pediatric Orthopaedics, 115-122, 2019.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic-slides.pdf">[slides]</a>'+
					' <a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2019-orthopaedic-walking-basic.pdf">[article]</a>',
		'type': 'talk',
	},
	{
		'title': '데이터 기반 보행 제어를 위한 다리 간 충돌 회피 기법',
		'representative_img': 'assets/publications/domestic/2017-kcgsjournal-inter-leg.png',
		'year': 2017,
		'authors': '이윤상',
		'conference_journal_full': '컴퓨터그래픽스학회논문지, 제23권 제2호, 23-27, 2017.06.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2017-kcgsjournal-inter-leg.pdf">[article]</a>',
		'type': 'paper',
	},
	{
		'title': 'Make It Walk!: Locomotion Control',
		'representative_img': 'assets/publications/domestic/2016-kcgs-make-it-walk.png',
		'year': 2016,
		'authors': '이윤상',
		'conference_journal_full': '한국컴퓨터그래픽스학회 2016년 학술대회 초청강연, 2016.07.',
		'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2016-kcgs-make-it-walk.pdf">[slides]</a>',
		'type': 'talk',
	},
]
