var senior_projs = [
	{
		'title': 'Phase-Functioned Neural Network in Unreal Engine 4',
		'authors': '이상옥, 구교민, 유지원',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team3',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/3tzndxUZ1RI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Autonomous Indoor Mapping using ROS Mobile Robot',
		'authors': '오동원',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team7',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/_6K3sdZhaQ0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Folding House',
		'authors': '조태희',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team8',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/jzDPYtdNXcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Goldberg Machine Animation in Blender',
		'authors': '임교리, 문정현',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team9',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="396" src="https://www.youtube.com/embed/nx8_TXvbTSQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
]
