var seniorprojs = [
	{
		'title': 'Team3',
		'topic': 'Unreal Engine 4 환경에서 Phase Functioned Neural Network 기술을 이용한 게임 제작',
		'authors': '이상옥, 구교민, 유지원',
		'project_page': 'courses/2019-fall-senior.html#Team3',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/3tzndxUZ1RI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Team7',
		'topic': 'ROS 기반 이동 로봇을 이용한 실내 지도 작성',
		'authors': '오동원',
		'project_page': 'courses/2019-fall-senior.html#Team7',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/_6K3sdZhaQ0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Team8',
		'topic': 'Folding House',
		'authors': '조태희',
		'project_page': 'courses/2019-fall-senior.html#Team8',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/jzDPYtdNXcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Team9',
		'topic': 'Blender를 이용한 Goldberg machine 애니메이션 제작',
		'authors': '임교리, 문정현',
		'project_page': 'courses/2019-fall-senior.html#Team9',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="396" src="https://www.youtube.com/embed/nx8_TXvbTSQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
]
