var senior_projs = [
	{
		'title': 'Physically simulated character controlled by SIMBICON algorithm in Dartpy and Blender environment',
		'authors': '사정',
		'project_page': 'courses/2020-fall-senior.html',
		'id': 'team3',
		'year': 2020,
		'season': 'fall',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/WcT76vsF-JY" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Locomotion control for OP3 robot in ROS environment using SIMBICON algorithm',
		'authors': '강정구, 곽상원, 김형순',
		'project_page': 'courses/2020-fall-senior.html',
		'id': 'team5',
		'year': 2020,
		'season': 'fall',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/WDXp9LuSiyA" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Comparison of ES(Evolutionary Strategy() and PPO(Proximal Policy Optimization() with standard DRL benchmarks',
		'authors': '정근욱, 황정태',
		'project_page': 'courses/2020-fall-senior.html',
		'id': 'team6',
		'year': 2020,
		'season': 'fall',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/m7EbHigIkfI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'A worm-like softbody creature simulated using FEM and learned using deep reinforcement learning',
		'authors': '백종운, 최기곤, 김환진',
		'project_page': 'courses/2020-fall-senior.html',
		'id': 'team8',
		'year': 2020,
		'season': 'fall',
		'video_iframe': '<iframe width="1280" height="720" src="https://www.youtube.com/embed/fQ-Zf69X4Sc" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Phase-Functioned Neural Network in Unreal Engine 4',
		'authors': '이상옥, 구교민, 유지원',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team3',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/3tzndxUZ1RI" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Autonomous Indoor Mapping using ROS Mobile Robot',
		'authors': '오동원',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team7',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/_6K3sdZhaQ0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Folding House',
		'authors': '조태희',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team8',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="445" src="https://www.youtube.com/embed/jzDPYtdNXcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
	{
		'title': 'Goldberg Machine Animation in Blender',
		'authors': '임교리, 문정현',
		'project_page': 'courses/2019-fall-senior.html',
		'id': 'team9',
		'year': 2019,
		'season': 'fall',
		'video_iframe': '<iframe width="791" height="396" src="https://www.youtube.com/embed/nx8_TXvbTSQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>',
		'type': 'senior',
	},
]
